# -----------------------------------------------------------------------------
# ‚öôÔ∏è Site Settings
# -----------------------------------------------------------------------------

title: Professor Akram
email: akram-burris@utulsa.edu
description: >-
  A Master of Systemic Sorcery: Weaving the impossible creations of the 
  imagination into real-time experiences, controlling the entropy of 
  virtual worlds through the ancient art of Programming and Modular Systems Design.

# Branding & Social
twitter_username: ProfessorAkram 
github_username:  ProfessorAkram

# -----------------------------------------------------------------------------
# üõ†Ô∏è Build Settings
# -----------------------------------------------------------------------------

baseurl: "" 
url: "https://professorakram.github.io"

markdown: kramdown
remote_theme: "mmistakes/minimal-mistakes"
include: ["_pages"] # This tells Jekyll to look inside your _pages folder

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-remote-theme
  - jekyll-include-cache

# -----------------------------------------------------------------------------
# üé® Theme Settings
# -----------------------------------------------------------------------------

minimal_mistakes_skin: "dark"
site_author: "Professor Akram"
paginate: 5
words_per_minute: 200

# Masthead (Top Navigation) Settings
logo: "/assets/images/professor-akram-logo.png" # Path to your logo file
title: "Professor Akram"                      # Text that appears next to the logo 

# Defaults for Posts and Pages
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true

# -----------------------------------------------------------------------------
# üë§ Author Settings
# -----------------------------------------------------------------------------

author:
  name   : "Akram Taghavi-Burris"
  avatar : "/assets/images/2024-Akram.png"
  bio    : "Program Director & Professor of CSG | Master of Systems Sorcery."
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/ProfessorAkram"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/akram-taghavi-burris/"

# -----------------------------------------------------------------------------
# üö´ Exclusions
# -----------------------------------------------------------------------------

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .jekyll-cache
  - .jekyll-metadata